### ISSUE TITLE
두?

### ISSUE THREAD

**Issue by NY0510** [sqlare/attackhelicopter#2]
뀨?

**Comment by imnyang** [comment]
미테테네~❣️콘나 칸지데!⭐️후와후와~🌸퓨어퓨어~💙미라크루~🪄~뀽💘! 오므라이스상🍝~오이시쿠🍴나~~~레💙💙💙💙

**Comment by 10kwon** [comment]
> 뀨?

![두두두두두두두두두두두두두두두두두두두두두두두두두두두두두두두두두두두두두두두두두두두두두두두두두두두두두두두두두두두두두두두두두두두두두두두두두두두두두두두두두두두두두두두두두두두두두두두두두두두두두두두두두두두두두두두두두두두두두두두두두두두두두두두두두](https://github.com/imnyang/attackhelicopter/assets/110745857/81494ea1-f8c5-46e2-a7ec-bb18396a81f8)

**Comment by NOOBNUBY** [comment]
미테테네~❣️콘나 칸지데!⭐️후와후와~🌸퓨어퓨어💙미라크루~🪄~뀽💘! 오므라이스상🍝오이시쿠🍴나~~~레💙💙💙💙

**Comment by NOOBNUBY** [comment]
이게 뭐임 ;;
